name: 'deploy docker'

on:
  push:
    tags:
      - "*"

jobs:

  release-docker-image-job:
    runs-on: ubuntu-latest
    permissions: write-all  
    steps:
      - uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'container-m1'
      DOCKER_IMAGE_URL: 'ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}'
    steps:
      - name: Execute SSH commands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'superuser@123.253.62.249'
          privateKey: ${{ secrets.My_PRIVATE_KEY }}
          command: |
            sudo docker logout ghcr.io
            sudo docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
            sudo docker rm -f ${{ env.CONTAINER_NAME }} || true  
            sudo docker pull ${{ env.DOCKER_IMAGE_URL }}
            sudo docker run --restart=always -d --name ${{ env.CONTAINER_NAME }} -p 9011:3000 ${{ env.DOCKER_IMAGE_URL }}
          debug: true  
